// ignore_for_file: scoped_providers_should_specify_dependencies
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:verily_app/src/features/auth/auth_provider.dart';
import 'package:verily_app/src/features/settings/settings_screen.dart';
import 'package:verily_test_utils/verily_test_utils.dart';

// TODO(auth): These tests require `auth_provider.g.dart` to be generated.
// Run `dart run build_runner build` in the verily_app package before running.
// The `authProvider` is generated by riverpod_generator and is required by
// SettingsScreen via `ref.listen(authProvider, ...)`.

void main() {
  group('SettingsScreen', () {
    ProviderContainer buildContainer() {
      return ProviderContainer(
        overrides: [
          authProvider.overrideWith(() {
            return _FakeAuth();
          }),
        ],
      );
    }

    Future<void> pumpSettingsScreen(WidgetTester tester) async {
      await tester.pumpApp(const SettingsScreen(), container: buildContainer());
    }

    Future<void> scrollTo(WidgetTester tester, Finder finder) async {
      await tester.scrollUntilVisible(
        finder,
        300,
        scrollable: find.byType(Scrollable).first,
      );
      await tester.pumpAndSettle();
    }

    testWidgets('renders Settings app bar title', (tester) async {
      await pumpSettingsScreen(tester);

      expect(find.text('Settings'), findsOneWidget);
    });

    testWidgets('renders Appearance section with Theme', (tester) async {
      await pumpSettingsScreen(tester);

      expect(find.text('Appearance'), findsOneWidget);
      expect(find.text('Theme'), findsOneWidget);
    });

    testWidgets('renders theme mode options', (tester) async {
      await pumpSettingsScreen(tester);

      expect(find.text('System'), findsOneWidget);
      expect(find.text('Light'), findsOneWidget);
      expect(find.text('Dark'), findsOneWidget);
    });

    testWidgets('renders theme icons', (tester) async {
      await pumpSettingsScreen(tester);

      expect(find.byIcon(Icons.brightness_auto_outlined), findsOneWidget);
      expect(find.byIcon(Icons.light_mode_outlined), findsOneWidget);
      expect(find.byIcon(Icons.dark_mode_outlined), findsOneWidget);
    });

    testWidgets('renders Notifications section', (tester) async {
      await pumpSettingsScreen(tester);

      expect(find.text('Notifications'), findsOneWidget);
      expect(find.text('Push Notifications'), findsOneWidget);
      expect(
        find.text('Get notified about submissions and verifications'),
        findsOneWidget,
      );
    });

    testWidgets('renders Privacy section', (tester) async {
      await pumpSettingsScreen(tester);

      expect(find.text('Privacy'), findsOneWidget);
      expect(find.text('Location Sharing'), findsOneWidget);
      expect(find.text('Public Profile'), findsOneWidget);
    });

    testWidgets('renders About section', (tester) async {
      await pumpSettingsScreen(tester);
      await scrollTo(tester, find.text('About Verily'));

      expect(find.text('About'), findsOneWidget);
      expect(find.text('About Verily'), findsOneWidget);
      expect(find.text('Version 1.0.0'), findsOneWidget);
    });

    testWidgets('renders Terms of Service tile', (tester) async {
      await pumpSettingsScreen(tester);
      await scrollTo(tester, find.text('Terms of Service'));

      expect(find.text('Terms of Service'), findsOneWidget);
    });

    testWidgets('renders Privacy Policy tile', (tester) async {
      await pumpSettingsScreen(tester);
      await scrollTo(tester, find.text('Privacy Policy'));

      expect(find.text('Privacy Policy'), findsOneWidget);
    });

    testWidgets('renders Open Source Licenses tile', (tester) async {
      await pumpSettingsScreen(tester);
      await scrollTo(tester, find.text('Open Source Licenses'));

      expect(find.text('Open Source Licenses'), findsOneWidget);
    });

    testWidgets('renders Log Out button', (tester) async {
      await pumpSettingsScreen(tester);
      await scrollTo(tester, find.text('Log Out'));

      expect(find.text('Log Out'), findsOneWidget);
      expect(find.byIcon(Icons.logout), findsOneWidget);
    });

    testWidgets('renders toggle switches for notifications and privacy', (
      tester,
    ) async {
      await pumpSettingsScreen(tester);

      // There should be 3 SwitchListTile widgets:
      // Push Notifications, Location Sharing, Public Profile.
      expect(find.byType(SwitchListTile), findsNWidgets(3));
    });
  });
}

/// Fake Auth notifier that starts in [Unauthenticated] state.
class _FakeAuth extends Auth {
  @override
  AuthState build() => const Unauthenticated();

  @override
  Future<void> login({required String email, required String password}) async {}

  @override
  Future<void> loginWithGoogle() async {}

  @override
  Future<void> loginWithApple() async {}

  @override
  Future<void> logout() async {}

  @override
  Future<void> register({
    required String email,
    required String password,
  }) async {}
}
