// ignore_for_file: scoped_providers_should_specify_dependencies
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:verily_app/src/features/auth/auth_provider.dart';
import 'package:verily_app/src/features/auth/login_screen.dart';
import 'package:verily_test_utils/verily_test_utils.dart';

// TODO(auth): These tests require `auth_provider.g.dart` to be generated.
// Run `dart run build_runner build` in the verily_app package before running.
// The `authProvider` is generated by riverpod_generator and is required by
// LoginScreen via `ref.watch(authProvider)`.

void main() {
  group('LoginScreen', () {
    // Override the authProvider so it starts in Unauthenticated state
    // instead of AuthLoading (which would show loading spinners).
    late ProviderContainer container;

    setUp(() {
      container = ProviderContainer(
        overrides: [
          authProvider.overrideWith(() {
            return _FakeAuth();
          }),
        ],
      );
    });

    tearDown(() {
      container.dispose();
    });

    Future<void> pumpLoginScreen(WidgetTester tester) async {
      await tester.pumpApp(const LoginScreen(), container: container);
    }

    testWidgets('renders email text field', (tester) async {
      await pumpLoginScreen(tester);

      // The email VTextField has labelText: 'Email'
      expect(find.text('Email'), findsOneWidget);
      expect(find.text('you@example.com'), findsOneWidget);
    });

    testWidgets('renders password text field', (tester) async {
      await pumpLoginScreen(tester);

      // The password VTextField has labelText: 'Password'
      expect(find.text('Password'), findsOneWidget);
      expect(find.text('Enter your password'), findsOneWidget);
    });

    testWidgets('renders login button', (tester) async {
      await pumpLoginScreen(tester);

      expect(find.text('Log In'), findsOneWidget);
    });

    testWidgets('renders Google social login button', (tester) async {
      await pumpLoginScreen(tester);

      expect(find.text('Google'), findsOneWidget);
      expect(find.byIcon(Icons.g_mobiledata), findsOneWidget);
    });

    testWidgets('renders Apple social login button', (tester) async {
      await pumpLoginScreen(tester);

      expect(find.text('Apple'), findsOneWidget);
      expect(find.byIcon(Icons.apple), findsOneWidget);
    });

    testWidgets('renders register link with Sign Up text', (tester) async {
      await pumpLoginScreen(tester);

      expect(find.text("Don't have an account?"), findsOneWidget);
      expect(find.text('Sign Up'), findsOneWidget);
    });

    testWidgets('shows disabled X button with Coming soon tooltip', (
      tester,
    ) async {
      await pumpLoginScreen(tester);

      // The X button should be present but disabled (onPressed: null)
      expect(find.text('X'), findsOneWidget);
      expect(find.byIcon(Icons.close), findsOneWidget);
    });

    testWidgets('shows disabled Facebook button with Coming soon tooltip', (
      tester,
    ) async {
      await pumpLoginScreen(tester);

      expect(find.text('Facebook'), findsOneWidget);
      expect(find.byIcon(Icons.facebook), findsOneWidget);
    });

    testWidgets('renders app branding elements', (tester) async {
      await pumpLoginScreen(tester);

      expect(find.text('Verily'), findsOneWidget);
      expect(find.text('Verify real-world actions with AI'), findsOneWidget);
      expect(find.byIcon(Icons.verified_rounded), findsOneWidget);
    });

    testWidgets('renders or continue with divider', (tester) async {
      await pumpLoginScreen(tester);

      expect(find.text('or continue with'), findsOneWidget);
    });
  });
}

/// Fake Auth notifier that starts in [Unauthenticated] state.
class _FakeAuth extends Auth {
  @override
  AuthState build() => const Unauthenticated();

  @override
  Future<void> login({required String email, required String password}) async {}

  @override
  Future<void> loginWithGoogle() async {}

  @override
  Future<void> loginWithApple() async {}

  @override
  Future<void> logout() async {}

  @override
  Future<void> register({
    required String email,
    required String password,
  }) async {}
}
