// Test overrides don't need scoped provider dependencies.
// ignore_for_file: scoped_providers_should_specify_dependencies
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:verily_app/src/features/auth/auth_provider.dart';
import 'package:verily_app/src/features/auth/register_screen.dart';
import 'package:verily_test_utils/verily_test_utils.dart';

// TODO(auth): These tests require `auth_provider.g.dart` to be generated.
// Run `dart run build_runner build` in the verily_app package before running.
// The `authProvider` is generated by riverpod_generator and is required by
// RegisterScreen via `ref.watch(authProvider)`.

void main() {
  group('RegisterScreen', () {
    late ProviderContainer container;

    setUp(() {
      container = ProviderContainer(
        overrides: [
          authProvider.overrideWith(() {
            return _FakeAuth();
          }),
        ],
      );
    });

    tearDown(() {
      container.dispose();
    });

    Future<void> pumpRegisterScreen(WidgetTester tester) async {
      await tester.pumpApp(const RegisterScreen(), container: container);
    }

    testWidgets('renders email text field', (tester) async {
      await pumpRegisterScreen(tester);

      expect(find.text('Email'), findsOneWidget);
      expect(find.text('you@example.com'), findsOneWidget);
    });

    testWidgets('renders password text field', (tester) async {
      await pumpRegisterScreen(tester);

      expect(find.text('Password'), findsOneWidget);
      expect(find.text('At least 8 characters'), findsOneWidget);
    });

    testWidgets('renders confirm password text field', (tester) async {
      await pumpRegisterScreen(tester);

      expect(find.text('Confirm Password'), findsOneWidget);
      expect(find.text('Re-enter your password'), findsOneWidget);
    });

    testWidgets('renders Continue button on credentials step', (tester) async {
      await pumpRegisterScreen(tester);

      // On the first step (credentials), the button says "Continue".
      expect(find.text('Continue'), findsOneWidget);
    });

    testWidgets('renders login link with Log In text', (tester) async {
      await pumpRegisterScreen(tester);

      expect(find.text('Already have an account?'), findsOneWidget);
      expect(find.text('Log In'), findsOneWidget);
    });

    testWidgets('renders app bar with Create Account title', (tester) async {
      await pumpRegisterScreen(tester);

      expect(find.text('Create Account'), findsOneWidget);
    });

    testWidgets('renders step indicators', (tester) async {
      await pumpRegisterScreen(tester);

      // Step 1 indicator: "Credentials" label
      expect(find.text('Credentials'), findsOneWidget);
      // Step 2 indicator: "Verify" label
      expect(find.text('Verify'), findsOneWidget);
      // Step numbers
      expect(find.text('1'), findsOneWidget);
      expect(find.text('2'), findsOneWidget);
    });

    testWidgets('renders back arrow button', (tester) async {
      await pumpRegisterScreen(tester);

      expect(find.byIcon(Icons.arrow_back), findsOneWidget);
    });
  });
}

/// Fake Auth notifier that starts in [Unauthenticated] state.
class _FakeAuth extends Auth {
  @override
  AuthState build() => const Unauthenticated();

  @override
  Future<void> login({required String email, required String password}) async {}

  @override
  Future<void> loginWithGoogle() async {}

  @override
  Future<void> loginWithApple() async {}

  @override
  Future<void> logout() async {}

  @override
  Future<void> register({
    required Object accountRequestId,
    required String verificationCode,
    required String password,
  }) async {}
}
