include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_protocol/**"
    - "**/generated/**"
    - "**/.dart_tool/**"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
