import 'package:freezed_annotation/freezed_annotation.dart';

part 'ai_generated_action.freezed.dart';
part 'ai_generated_action.g.dart';

/// An action generated by AI from natural language input.
@freezed
abstract class AiGeneratedAction with _$AiGeneratedAction {
  const factory AiGeneratedAction({
    required String title,
    required String description,
    required String actionType,
    required String verificationCriteria,
    required String suggestedCategory,
    int? suggestedSteps,
    int? suggestedIntervalDays,
    @Default([]) List<String> suggestedTags,
    AiGeneratedLocation? suggestedLocation,
  }) = _AiGeneratedAction;

  factory AiGeneratedAction.fromJson(Map<String, dynamic> json) =>
      _$AiGeneratedActionFromJson(json);
}

/// A location suggested by AI for an action.
@freezed
abstract class AiGeneratedLocation with _$AiGeneratedLocation {
  const factory AiGeneratedLocation({
    required String name,
    required String address,
    required double latitude,
    required double longitude,
    @Default(100.0) double suggestedRadiusMeters,
  }) = _AiGeneratedLocation;

  factory AiGeneratedLocation.fromJson(Map<String, dynamic> json) =>
      _$AiGeneratedLocationFromJson(json);
}

/// A step generated by AI for a sequential action.
@freezed
abstract class AiGeneratedStep with _$AiGeneratedStep {
  const factory AiGeneratedStep({
    required int stepNumber,
    required String title,
    required String description,
    required String verificationCriteria,
  }) = _AiGeneratedStep;

  factory AiGeneratedStep.fromJson(Map<String, dynamic> json) =>
      _$AiGeneratedStepFromJson(json);
}
