import 'dart:io';

const _sourceDir = 'verily_app/lib/src';
const _arbPath = 'verily_app/lib/l10n/app_en.arb';
const _baselinePath = 'tools/localized_ui_text_baseline.txt';

final _textLiteralPattern = RegExp(
  r'''(?:Text|SelectableText)\(\s*(?:const\s*)?(['"])([^'"]*)\1''',
);

final _namedLiteralPattern = RegExp(
  r'''\b(?:label|title|hintText|labelText|helperText|tooltip|semanticLabel)\s*:\s*(?:const\s*)?(['"])([^'"]*)\1''',
);

final _violationPattern = RegExp(r'^(.+?):\d+:\s+hardcoded UI text\s+"(.*)"$');

void main(List<String> args) {
  final updateBaseline = args.contains('--update-baseline');
  final strict = args.contains('--strict');

  final root = Directory.current;
  final sourceRoot = Directory('${root.path}/$_sourceDir');

  if (!sourceRoot.existsSync()) {
    stderr.writeln(
      'Missing source directory: ${sourceRoot.path}. Run from repo root.',
    );
    exitCode = 2;
    return;
  }

  final violations = _scanViolations(root: root, sourceRoot: sourceRoot)
    ..sort();
  final currentSignatures = violations.map(_signatureForViolation).toSet();

  if (updateBaseline) {
    _writeBaseline(root, currentSignatures);
    stdout.writeln(
      'Updated $_baselinePath with ${currentSignatures.length} known violations.',
    );
    return;
  }

  if (violations.isEmpty) {
    stdout.writeln('No hardcoded UI text detected in $_sourceDir.');
    return;
  }

  if (strict) {
    _printStrictFailure(violations);
    exitCode = 1;
    return;
  }

  final baselineFile = File('${root.path}/$_baselinePath');
  if (!baselineFile.existsSync()) {
    _printStrictFailure(violations);
    stderr
      ..writeln()
      ..writeln(
        'Baseline file missing. To establish a baseline for existing debt, run:',
      )
      ..writeln(
        '  dart run tools/check_localized_ui_text.dart --update-baseline',
      );
    exitCode = 1;
    return;
  }

  final baseline = _readBaseline(baselineFile);
  final newViolations = violations
      .where(
        (violation) => !baseline.contains(_signatureForViolation(violation)),
      )
      .toList();
  final resolvedBaselineEntries = baseline.difference(currentSignatures);

  if (newViolations.isEmpty) {
    stdout.writeln('No new hardcoded UI text detected in $_sourceDir.');
    if (resolvedBaselineEntries.isNotEmpty) {
      stdout.writeln(
        'Note: ${resolvedBaselineEntries.length} baseline entries are now resolved. '
        'Run --update-baseline to keep $_baselinePath clean.',
      );
    }
    return;
  }

  stderr.writeln(
    'Found NEW hardcoded UI text. Add strings to $_arbPath and use AppLocalizations.',
  );
  for (final violation in newViolations) {
    stderr.writeln(violation);
  }

  if (resolvedBaselineEntries.isNotEmpty) {
    stderr
      ..writeln()
      ..writeln(
        'Note: ${resolvedBaselineEntries.length} baseline entries are now resolved. '
        'Run --update-baseline after cleaning remaining violations.',
      );
  }

  exitCode = 1;
}

List<String> _scanViolations({
  required Directory root,
  required Directory sourceRoot,
}) {
  final violations = <String>[];
  final files = sourceRoot
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('.dart'));

  for (final file in files) {
    final lines = file.readAsLinesSync();
    for (var index = 0; index < lines.length; index++) {
      final line = lines[index];
      if (line.contains('// l10n-ignore')) continue;

      for (final pattern in [_textLiteralPattern, _namedLiteralPattern]) {
        for (final match in pattern.allMatches(line)) {
          final literal = match.group(2) ?? '';
          if (_shouldIgnoreLiteral(literal)) continue;
          final relativePath = file.path.replaceFirst('${root.path}/', '');
          violations.add(
            '$relativePath:${index + 1}: hardcoded UI text "$literal"',
          );
        }
      }
    }
  }

  return violations;
}

void _writeBaseline(Directory root, Set<String> signatures) {
  final file = File('${root.path}/$_baselinePath');
  final sortedSignatures = signatures.toList()..sort();

  final buffer = StringBuffer()
    ..writeln('# Baseline for existing hardcoded UI text violations.')
    ..writeln('#')
    ..writeln(
      '# Generated by: dart run tools/check_localized_ui_text.dart --update-baseline',
    )
    ..writeln('# Format: <relative/path.dart>::<literal>')
    ..writeln('# Any signature not listed here will fail lint:l10n.')
    ..writeln();

  for (final signature in sortedSignatures) {
    buffer.writeln(signature);
  }

  file.parent.createSync(recursive: true);
  file
    ..createSync()
    ..writeAsStringSync(buffer.toString());
}

Set<String> _readBaseline(File file) {
  final entries = <String>{};
  for (final raw in file.readAsLinesSync()) {
    final line = raw.trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    entries.add(_normalizeBaselineEntry(line));
  }
  return entries;
}

String _normalizeBaselineEntry(String entry) {
  if (entry.contains('::')) {
    return entry;
  }
  return _signatureForViolation(entry);
}

String _signatureForViolation(String violation) {
  final match = _violationPattern.firstMatch(violation);
  if (match == null) return violation;
  final path = match.group(1) ?? '';
  final literal = match.group(2) ?? '';
  return '$path::$literal';
}

void _printStrictFailure(List<String> violations) {
  stderr.writeln(
    'Found hardcoded UI text. Add strings to $_arbPath and use AppLocalizations.',
  );
  for (final violation in violations) {
    stderr.writeln(violation);
  }
}

bool _shouldIgnoreLiteral(String literal) {
  if (literal.trim().isEmpty) return true;
  if (literal.contains(r'$')) return true;
  if (RegExp(r'^\d+$').hasMatch(literal)) return true;
  if (RegExp(r'^[^\w]+$').hasMatch(literal)) return true;
  return false;
}
